using System.Data.Common;
using System.Text.Json;
using Archit.Api.Infrastructure;

namespace Archit.Api.Projects;

public sealed class PostgresProjectRepository(IArchitDbConnectionFactory connections) : IProjectRepository
{
    public async Task<ProjectRecord> CreateAsync(string name,Guid? tenantId,CancellationToken cancellationToken)
    {
        var now=DateTimeOffset.UtcNow;var project=new ProjectRecord(Guid.NewGuid(),tenantId,name.Trim(),now,now);
        await using var connection=await connections.OpenAsync(cancellationToken);await using var command=connection.CreateCommand();command.CommandText="INSERT INTO projects(id,tenant_id,name,created_at,updated_at) VALUES(@id,@tenant,@name,@created,@updated)";Add(command,"id",project.Id);Add(command,"tenant",project.TenantId);Add(command,"name",project.Name);Add(command,"created",project.CreatedAt);Add(command,"updated",project.UpdatedAt);await command.ExecuteNonQueryAsync(cancellationToken);return project;
    }
    public async Task<ProjectRecord?> GetAsync(Guid projectId,CancellationToken cancellationToken){await using var connection=await connections.OpenAsync(cancellationToken);await using var command=connection.CreateCommand();command.CommandText=ProjectSelect+" WHERE id=@id";Add(command,"id",projectId);await using var reader=await command.ExecuteReaderAsync(cancellationToken);return await reader.ReadAsync(cancellationToken)?ReadProject(reader):null;}
    public async Task<IReadOnlyList<ProjectRecord>> ListAsync(CancellationToken cancellationToken){await using var connection=await connections.OpenAsync(cancellationToken);await using var command=connection.CreateCommand();command.CommandText=ProjectSelect+" ORDER BY updated_at DESC";await using var reader=await command.ExecuteReaderAsync(cancellationToken);var items=new List<ProjectRecord>();while(await reader.ReadAsync(cancellationToken))items.Add(ReadProject(reader));return items;}
    public async Task<ProjectRevision> AddRevisionAsync(Guid projectId,CreateRevisionRequest request,CancellationToken cancellationToken)
    {
        await using var connection=await connections.OpenAsync(cancellationToken);await using var transaction=await connection.BeginTransactionAsync(cancellationToken);if(!await Exists(connection,transaction,"SELECT 1 FROM projects WHERE id=@id",projectId,cancellationToken))throw new KeyNotFoundException($"Project {projectId} was not found.");if(request.ParentRevisionId is Guid parentId&&!await Exists(connection,transaction,"SELECT 1 FROM project_revisions WHERE id=@id AND project_id=@project",parentId,cancellationToken,projectId))throw new InvalidOperationException($"Parent revision {parentId} does not belong to project {projectId}.");var revision=new ProjectRevision(Guid.NewGuid(),projectId,request.ParentRevisionId,request.Kind.Trim(),DateTimeOffset.UtcNow,request.CreatedBy.Trim(),request.SourceImportId,request.Model.Clone(),request.Note);
        await using(var insert=connection.CreateCommand()){insert.Transaction=transaction;insert.CommandText="INSERT INTO project_revisions(id,project_id,parent_revision_id,kind,created_at,created_by,source_import_id,model,note) VALUES(@id,@project,@parent,@kind,@created,@by,@source,CAST(@model AS jsonb),@note)";Add(insert,"id",revision.Id);Add(insert,"project",projectId);Add(insert,"parent",revision.ParentRevisionId);Add(insert,"kind",revision.Kind);Add(insert,"created",revision.CreatedAt);Add(insert,"by",revision.CreatedBy);Add(insert,"source",revision.SourceImportId);Add(insert,"model",revision.Model.GetRawText());Add(insert,"note",revision.Note);await insert.ExecuteNonQueryAsync(cancellationToken);}await using(var update=connection.CreateCommand()){update.Transaction=transaction;update.CommandText="UPDATE projects SET updated_at=@updated WHERE id=@id";Add(update,"updated",revision.CreatedAt);Add(update,"id",projectId);await update.ExecuteNonQueryAsync(cancellationToken);}await transaction.CommitAsync(cancellationToken);return revision;
    }
    public async Task<ProjectRevision?> GetRevisionAsync(Guid projectId,Guid revisionId,CancellationToken cancellationToken){await using var connection=await connections.OpenAsync(cancellationToken);await using var command=connection.CreateCommand();command.CommandText=RevisionSelect+" WHERE project_id=@project AND id=@id";Add(command,"project",projectId);Add(command,"id",revisionId);await using var reader=await command.ExecuteReaderAsync(cancellationToken);return await reader.ReadAsync(cancellationToken)?ReadRevision(reader):null;}
    public async Task<IReadOnlyList<ProjectRevision>> ListRevisionsAsync(Guid projectId,CancellationToken cancellationToken){await using var connection=await connections.OpenAsync(cancellationToken);if(!await Exists(connection,null,"SELECT 1 FROM projects WHERE id=@id",projectId,cancellationToken))throw new KeyNotFoundException($"Project {projectId} was not found.");await using var command=connection.CreateCommand();command.CommandText=RevisionSelect+" WHERE project_id=@project ORDER BY created_at DESC";Add(command,"project",projectId);await using var reader=await command.ExecuteReaderAsync(cancellationToken);var items=new List<ProjectRevision>();while(await reader.ReadAsync(cancellationToken))items.Add(ReadRevision(reader));return items;}
    private const string ProjectSelect="SELECT id,tenant_id,name,created_at,updated_at FROM projects";private const string RevisionSelect="SELECT id,project_id,parent_revision_id,kind,created_at,created_by,source_import_id,model::text,note FROM project_revisions";
    private static ProjectRecord ReadProject(DbDataReader r)=>new(r.GetGuid(0),r.IsDBNull(1)?null:r.GetGuid(1),r.GetString(2),r.GetFieldValue<DateTimeOffset>(3),r.GetFieldValue<DateTimeOffset>(4));
    private static ProjectRevision ReadRevision(DbDataReader r){using var doc=JsonDocument.Parse(r.GetString(7));return new ProjectRevision(r.GetGuid(0),r.GetGuid(1),r.IsDBNull(2)?null:r.GetGuid(2),r.GetString(3),r.GetFieldValue<DateTimeOffset>(4),r.GetString(5),r.IsDBNull(6)?null:r.GetGuid(6),doc.RootElement.Clone(),r.IsDBNull(8)?null:r.GetString(8));}
    private static async Task<bool> Exists(DbConnection connection,DbTransaction? transaction,string sql,Guid id,CancellationToken ct,Guid? projectId=null){await using var command=connection.CreateCommand();command.Transaction=transaction;command.CommandText=sql;Add(command,"id",id);if(projectId.HasValue)Add(command,"project",projectId.Value);return await command.ExecuteScalarAsync(ct)is not null;}
    private static void Add(DbCommand command,string name,object? value){var parameter=command.CreateParameter();parameter.ParameterName="@"+name;parameter.Value=value??DBNull.Value;command.Parameters.Add(parameter);}
}
